var trans={DefaultLat:-27.46884,
    DefaultLng:-58.823386,
    DefaultAddress:"Junín 2175, Corrientes, Argentina",
    Geolocation:"Geolocalización:",
    Latitude:"Latitud:",
    Longitude:"Longitud:",
    GetAltitude:"Obtener Altitud",
    NoResolvedAddress:"Sin dirección resuelta",
    GeolocationError:"Error de geolocalización.",
    GeocodingError:"Error de codificación geográfica: ",
    Altitude:"Altitud: ",
    Meters:" metros",
    NoResult:"No se encontraron Resultados",
    ElevationFailure:"Elevation service failed due to: ",
    SetOrigin:"Establecer como origen",
    SetDestination:"Establecer como destino",
    Address:"Dirección: ",
    Bicycling:"En bicicleta",
    Transit:"Transporte público",
    Walking:"A pie",
    Driving:"En coche",
    Kilometer:"Kilómetro",
    Mile:"Milla",
    Avoid:"Evitar",
    DirectionsError:"Calculating error or invalid route.",
    North:"N",
    South:"S",
    East:"E",
    West:"O",
    Type:"tipo",
    Lat:"latitud",
    Lng:"longitud",
    Dd:"GD",
    Dms:"GMS",
    CheckMapDelay:7e3};